name: Build Vue WebApp

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install wasm-pack
      run:  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - uses: actions/checkout@v2

    - name: Set Git User info
      run: |
          git config --global user.email "some_name@example.com"
          git config --global user.name "A Name"

    - name: Run setup script
      run: bash ./setup.sh

    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        cname: 'memeasm.010.one'
        token: ${{ secrets.GITHUB_TOKEN }}
        username: 'xarantolus'
        reponame: 'MemeAssembly-playground'
