name: Build & Deploy Vue WebApp

on:
  push:
    branches: [ main ]

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true


jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build & Deploy to GH Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install wasm-pack
      run:  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set Git User info
      run: |
          git config --global user.email "some_name@example.com"
          git config --global user.name "A Name"

    - name: Run setup script
      run: bash ./setup.sh

    - name: Run build
      run: |
        npm run build
        cp CNAME dist

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
