name: Build Vue WebApp

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2

    - name: Run setup script
      run: bash ./setup.sh

    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        cname: 'memeasm.010.one'
        token: ${{ secrets.GITHUB_TOKEN }}
